issue #101
Clariteia/minos_microservice_saga pull request #102
Opened 2021-05-28 11:03 UTC by albamig

- First version of documentation.

This PR closes issue #101.

2021-05-28 11:36 UTC, garciparedes requested changes
Hi @albamig, the changes are really fine! But, I added you some comments about small bugs related with copy-pasting from `minos-microservice-common`. Could you fix it before I approve the Pull Request? 🤗

2021-05-28 11:36 UTC, garciparedes commented on docs/Makefile
> +SPHINXPROJ    = minos_microservice_common
I think this would be referred to the `minos-microservice-saga` repo, I am right?

2021-05-28 11:36 UTC, garciparedes commented on docs/conf.py
> +from minos import common
I think this would be referred to the `minos-microservice-saga` repo, I am right?

2021-05-28 11:36 UTC, garciparedes commented on docs/conf.py
> +project = 'Minos Microservice Common'
I think this would be referred to the `minos-microservice-saga` repo, I am right?

2021-05-31 09:13 UTC, garciparedes requested changes
Could you apply the the proposed change?

2021-05-31 09:13 UTC, garciparedes commented on docs/conf.py
> +     'Minos Microservice Common Documentation',
Shouldn't this be `Saga`?
```suggestion
     'Minos Microservice Saga Documentation',
```

2021-05-31 09:13 UTC, garciparedes commented on docs/conf.py
> +     'Minos Microservice Common Documentation',
Shouldn't this be `Saga`?
```suggestion
     'Minos Microservice Saga Documentation',
```

2021-05-31 09:13 UTC, garciparedes commented on docs/conf.py
> +     'Minos Microservice Common Documentation',
Shouldn't this be `Saga`?
```suggestion
     'Minos Microservice Saga Documentation',
```

2021-05-31 09:13 UTC, garciparedes commented on docs/make.bat
> +set SPHINXPROJ=minos_microservice_common
Shouldn't this be `minos_microservice_saga`?
```suggestion
set SPHINXPROJ=minos_microservice_saga
```

2021-05-31 09:13 UTC, garciparedes commented on docs/usage.rst
> +    import minos_microservice_common
```suggestion
    from minos import saga
```

2021-05-31 09:13 UTC, garciparedes commented on docs/conf.py
> +]
This is not needed here.
```suggestion
```

2021-05-31 09:13 UTC, garciparedes commented on README.md
> +![Tests](https://github.com/Clariteia/minos_microservice_common/actions/workflows/python-tests.yml/badge.svg)
```suggestion
[![codecov](https://codecov.io/gh/Clariteia/minos_microservice_saga/branch/main/graph/badge.svg)](https://codecov.io/gh/Clariteia/minos_microservice_saga)
![Tests](https://github.com/Clariteia/minos_microservice_saga/actions/workflows/python-tests.yml/badge.svg)
```

2021-05-31 09:25 UTC, garciparedes commented on docs/usage.rst
> +To use Minos Microservice Common in a project::
```suggestion
To use Minos Microservice Saga in a project::
```

2021-05-31 09:25 UTC, garciparedes commented on docs/conf.py
> +#     "github_repo": "minos_microservice_common",
```suggestion
#     "github_repo": "minos_microservice_saga",
```

2021-05-31 09:26 UTC, garciparedes approved these changes
Hi @albamig, good changes! I'm sure that these documentation improvements will really help us to leverage this project to the next level! 🚀

2021-05-31 09:39 UTC, merged

2021-05-31 09:39 UTC, albamig commented
Thank you for the thorough review @garciparedes :mag: